# coding: utf-8

"""
    IONOS Cloud - API Gateway

    API Gateway is an application that acts as a \"front door\" for backend services and APIs, handling client requests and routing them to the appropriate backend. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_api_gateway.models.gateway_custom_domains_inner import GatewayCustomDomainsInner
from typing import Optional, Set
from typing_extensions import Self

class Gateway(BaseModel):
    """
    An API gateway consists of the generic rules and configurations of an API Gateway. 
    """ # noqa: E501
    name: Optional[StrictStr] = None
    logs: Optional[StrictBool] = Field(default=None, description="This field enables or disables the collection and reporting of logs for observability of this instance.")
    metrics: Optional[StrictBool] = Field(default=None, description="This field enables or disables the collection and reporting of metrics for observability of this instance.")
    custom_domains: Optional[Annotated[List[GatewayCustomDomainsInner], Field(max_length=5)]] = Field(default=None, alias="customDomains")
    __properties: ClassVar[List[str]] = ["name", "logs", "metrics", "customDomains"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Gateway from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_domains (list)
        _items = []
        if self.custom_domains:
            for _item_custom_domains in self.custom_domains:
                if _item_custom_domains:
                    _items.append(_item_custom_domains.to_dict())
            _dict['customDomains'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Gateway from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "logs": obj.get("logs"),
            "metrics": obj.get("metrics"),
            "customDomains": [GatewayCustomDomainsInner.from_dict(_item) for _item in obj["customDomains"]] if obj.get("customDomains") is not None else None
        })
        return _obj


