# coding: utf-8

"""
    IONOS Cloud - API Gateway

    API Gateway is an application that acts as a \"front door\" for backend services and APIs, handling client requests and routing them to the appropriate backend. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_api_gateway.models.route_upstreams_inner import RouteUpstreamsInner
from typing import Optional, Set
from typing_extensions import Self

class Route(BaseModel):
    """
    A route is a rule that maps an incoming request to a specific backend service. 
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The name of the route.")
    type: Optional[StrictStr] = Field(default=None, description="This field specifies the protocol used by the ingress to route traffic to the backend service.")
    paths: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="The paths that the route should match. ")
    methods: Optional[List[StrictStr]] = Field(default=None, description="The HTTP methods that the route should match. ")
    websocket: Optional[StrictBool] = Field(default=None, description="To enable websocket support.")
    upstreams: Optional[Annotated[List[RouteUpstreamsInner], Field(min_length=1)]] = None
    __properties: ClassVar[List[str]] = ["name", "type", "paths", "methods", "websocket", "upstreams"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Route from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in upstreams (list)
        _items = []
        if self.upstreams:
            for _item_upstreams in self.upstreams:
                if _item_upstreams:
                    _items.append(_item_upstreams.to_dict())
            _dict['upstreams'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Route from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "paths": obj.get("paths"),
            "methods": obj.get("methods"),
            "websocket": obj.get("websocket"),
            "upstreams": [RouteUpstreamsInner.from_dict(_item) for _item in obj["upstreams"]] if obj.get("upstreams") is not None else None
        })
        return _obj


