# coding: utf-8

# flake8: noqa

"""
    IONOS Cloud - API Gateway

    API Gateway is an application that acts as a \"front door\" for backend services and APIs, handling client requests and routing them to the appropriate backend. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.1"

# import apis into sdk package
from ionoscloud_api_gateway.api.api_gateways_api import APIGatewaysApi
from ionoscloud_api_gateway.api.routes_api import RoutesApi

# import ApiClient
from ionoscloud_api_gateway.api_response import ApiResponse
from ionoscloud_api_gateway.api_client import ApiClient
from ionoscloud_api_gateway.configuration import Configuration
from ionoscloud_api_gateway.exceptions import OpenApiException
from ionoscloud_api_gateway.exceptions import ApiTypeError
from ionoscloud_api_gateway.exceptions import ApiValueError
from ionoscloud_api_gateway.exceptions import ApiKeyError
from ionoscloud_api_gateway.exceptions import ApiAttributeError
from ionoscloud_api_gateway.exceptions import ApiException

# import models into sdk package
from ionoscloud_api_gateway.models.error import Error
from ionoscloud_api_gateway.models.error_messages_inner import ErrorMessagesInner
from ionoscloud_api_gateway.models.gateway import Gateway
from ionoscloud_api_gateway.models.gateway_create import GatewayCreate
from ionoscloud_api_gateway.models.gateway_custom_domains_inner import GatewayCustomDomainsInner
from ionoscloud_api_gateway.models.gateway_ensure import GatewayEnsure
from ionoscloud_api_gateway.models.gateway_read import GatewayRead
from ionoscloud_api_gateway.models.gateway_read_list import GatewayReadList
from ionoscloud_api_gateway.models.links import Links
from ionoscloud_api_gateway.models.metadata import Metadata
from ionoscloud_api_gateway.models.metadata_with_endpoint import MetadataWithEndpoint
from ionoscloud_api_gateway.models.metadata_with_status import MetadataWithStatus
from ionoscloud_api_gateway.models.pagination import Pagination
from ionoscloud_api_gateway.models.route import Route
from ionoscloud_api_gateway.models.route_create import RouteCreate
from ionoscloud_api_gateway.models.route_ensure import RouteEnsure
from ionoscloud_api_gateway.models.route_read import RouteRead
from ionoscloud_api_gateway.models.route_read_list import RouteReadList
from ionoscloud_api_gateway.models.route_upstreams_inner import RouteUpstreamsInner
